# Generated by Django 4.2 on 2025-12-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Готовится'), ('ready', 'Готово')], db_column='status', default='pending', max_length=20),
        ),
    ]
