# Generated by Django 4.2 on 2025-12-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('here', 'Здесь'), ('takeaway', 'С собой'), ('delivery', 'Доставка')], db_column='order_type', default='here', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='options',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
