# Generated by Django 4.2 on 2025-12-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_product_cost_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(choices=[('lavash_m', 'M-лаваш'), ('lavash_l', 'Л-лаваш'), ('lavash_s', 'Сырный лаваш'), ('bun', 'Булочка'), ('strips', 'Стрипсы'), ('wings', 'Крылышки')], max_length=50)),
                ('delivered_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'supplies',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='ingredient_type',
            field=models.CharField(blank=True, choices=[('lavash_m', 'M-лаваш'), ('lavash_l', 'Л-лаваш'), ('lavash_s', 'Сырный лаваш'), ('bun', 'Булочка'), ('strips', 'Стрипсы'), ('wings', 'Крылышки')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredient_usage',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Сколько единиц ингредиента расходуется на одну порцию', max_digits=5),
        ),
    ]
