# Generated by Django 4.2 on 2025-12-26 11:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receipt_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DeletedItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cashier', models.ForeignKey(blank=True, db_column='cashier_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_items', to='orders.employee')),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='deleted_items', to='orders.order')),
            ],
            options={
                'db_table': 'deleted_items',
            },
        ),
    ]
