# Generated by Django 4.2 on 2025-12-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_cancelled_at_orderitem_cancelled_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='receipt_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
