# Generated by Django 4.2 on 2026-01-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_order_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
