# Generated by Django 4.2 on 2026-01-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_orderitem_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
