# Generated by Django 4.2 on 2026-01-04 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_orderitem_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='original_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
