# Generated by Django 4.2 on 2026-01-05 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_category_alter_order_status_dish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Dish',
        ),
    ]
